name: Noetic Ubuntu 20.04

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      ROS_CI_DESKTOP: "'lsb_release -cs'"
      ROS_DISTRO: noetic
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install ROS
        run: |
            sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main\" > /etc/apt/sources.list.d/ros-latest.list"
            sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
            sudo apt-get update -qq
            sudo apt-get install dpkg
            sudo apt-get install -y python3-catkin-pkg
            sudo apt-get install -y python3-catkin-tools
            sudo apt-get install -y python3-osrf-pycommon
            sudo apt-get install -y python3-rosdep
            sudo apt-get install -y python3-wstool
            sudo apt-get install -y ros-cmake-modules
            sudo apt-get install -y ros-noetic-turtlebot3
            sudo apt-get install -y ros-noetic-navigation
            sudo apt-get install -y ros-$ROS_DISTRO-catkin
            source /opt/ros/$ROS_DISTRO/setup.bash
      - name: Install ROS packages with rosdep
        run: |
            source /opt/ros/$ROS_DISTRO/setup.bash
            sudo rosdep init
            rosdep update
      - name: Create Workspace
        run: |
            mkdir catkin_ws
            mv `find -maxdepth 1 -not -name . -not -name catkin_ws` catkin_ws/
            mv catkin_ws/ src/
            cd src
            bash -c 'source /opt/ros/$ROS_DISTRO/setup.bash; \
            catkin init'
            rosdep install --from-paths src --ignore-src -r -s
            rosdep install --from-paths src --ignore-src -ry
      - name: catkin build
        run: |
            source /opt/ros/$ROS_DISTRO/setup.bash
            cd ~/catkin_ws
            catkin build
            source devel/setup.bash
